/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Medico;

import Controller.EspecialidadControlador;
import Controller.MedicoController;
import Controller.ValidacionController;
import Model.Especialidad;
import Model.Medico;
import Model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class IngresarMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingresar
     */
    
    ValidacionController validacion = ValidacionController.getinstancia();
    EspecialidadControlador especialdiadcontrol = EspecialidadControlador.getinstancia();
    MedicoController medicocontrol = MedicoController.getinstancia();
    Medico medico1;
    
    public IngresarMedico() {
        initComponents();
        EspecialidadLista();
    }
    
    public void EspecialidadLista()
    {
        cbx_Especilidad.addItem("SELECIONE UNA ESPECIALIDAD");
        for (Especialidad especialidad : especialdiadcontrol.listaEspecialidad()) {
            cbx_Especilidad.addItem(especialidad.getEspecialidad());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Edad = new javax.swing.JTextField();
        cbx_Especilidad = new javax.swing.JComboBox<>();
        cbx_Sexo = new javax.swing.JComboBox<>();
        btn_Guardar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Ingrese los Datos Requeridos");

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Especialidad");

        jLabel7.setText("Sexo");

        cbx_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Nombre)
                                    .addComponent(txt_Cedula)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(57, 57, 57)
                                .addComponent(txt_Edad))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_Especilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_Especilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Guardar)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar
        // TODO add your handling code here:
        String cedula = validacion.ValidacionCedula(txt_Cedula.getText());
        String nombre = validacion.ValidacionNombre(txt_Nombre.getText());
        int edad = validacion.ValidacionEdad(txt_Edad.getText());
        String especialidad = validacion.ValidarEspecialidadPorNombre(cbx_Especilidad.getSelectedItem().toString());
        //String especialidad = cbx_Especilidad.getSelectedItem().toString();
        boolean sexo = validacion.ValidacionSexo(cbx_Sexo.getSelectedItem().toString());
        boolean validado = validacion.VerificadorDeIngresoDeDatos(nombre, cedula, edad);
        int contador=0;
        
        if(validado == true)
        {
            for (Medico medico : medicocontrol.ListaMedico()) {
                if(medico.getCedula().contains(cedula) && medico.getNombre().contains(nombre))
                {
                    JOptionPane.showMessageDialog(this, "YA EXISTE UN MEDICO CON ESTOS DATOS");
                    contador++;
                }
            }
            if(contador!=1)
            {
                medico1 = medicocontrol.GuardarMedico(especialidad, cedula, nombre, edad, sexo);
                JOptionPane.showMessageDialog(this, "SE HA GUARDADO LOS DATOS CORRECTAMENTE DEL DR(A): "+medico1.getNombre());
                txt_Cedula.setText("");
                txt_Nombre.setText("");
                txt_Edad.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "NO SE HA PODIDO GUARDAR LOS DATOS");
        }
        txt_Cedula.setText("");
        txt_Nombre.setText("");
        txt_Edad.setText("");
    }//GEN-LAST:event_Guardar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox<String> cbx_Especilidad;
    private javax.swing.JComboBox<String> cbx_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
