/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Medico;

import Controller.MedicoController;
import Model.Medico;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ListadoMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listado
     */
    public DefaultTableModel model1 = new DefaultTableModel();
    MedicoController medico = MedicoController.getinstancia();
    
    public ListadoMedico() {
        initComponents();
        tbl_ListaMedico.setModel(model1);
        String [] Columnas = {"Cedula","Nombre","Especialdiad","Edad","Sexo"};
        model1.setColumnIdentifiers(Columnas);
        ListadoDoctores();
    }
    
    public void ListadoDoctores()
    {
        for (Medico medico1 : medico.ListaMedico()) {
            model1.addRow(new Object[] {medico1.getCedula(),medico1.getNombre(),medico1.getEspecialidad().getEspecialidad(),medico1.getEdad(),medico1.getSexo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_BuscarMedico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ListaMedico = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_BuscarPorNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_EliminarMedicoCedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_BuscarPorEspecialidad = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Listado de Medico");

        jLabel2.setText("Buscar Medico Por Cedula");

        txt_BuscarMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarMedicoKeyReleased(evt);
            }
        });

        tbl_ListaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_ListaMedico);

        jLabel3.setText("Buscar Medico Por Nombre");

        txt_BuscarPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarPorNombreKeyReleased(evt);
            }
        });

        jLabel4.setText("Eliminar Medico Por Cedula");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar(evt);
            }
        });

        jLabel5.setText("Buscar Medico Por Especialidad");

        txt_BuscarPorEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarPorEspecialidadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_BuscarPorEspecialidad))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_BuscarPorNombre)
                                    .addComponent(txt_BuscarMedico))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_EliminarMedicoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_BuscarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_EliminarMedicoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_BuscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_BuscarPorEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BuscarMedicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarMedicoKeyReleased
        // TODO add your handling code here:
        model1.setRowCount(0);
        for (Medico medico1 : medico.ListadoMedicoPorCedula(txt_BuscarMedico.getText())) {
            model1.addRow(new Object [] {medico1.getCedula(),medico1.getNombre(),medico1.getEspecialidad().getEspecialidad(),medico1.getEdad(),medico1.getSexo()});
        }
    }//GEN-LAST:event_txt_BuscarMedicoKeyReleased

    private void txt_BuscarPorNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarPorNombreKeyReleased
        // TODO add your handling code here:
        model1.setRowCount(0);
        for (Medico medico1 : medico.ListadoMedicoPorNombre(txt_BuscarPorNombre.getText())) {
            model1.addRow(new Object [] {medico1.getCedula(),medico1.getNombre(),medico1.getEspecialidad().getEspecialidad(),medico1.getEdad(),medico1.getSexo()});
        }
    }//GEN-LAST:event_txt_BuscarPorNombreKeyReleased

    private void Eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar
        // TODO add your handling code here:
        model1.setRowCount(0);
        for (Medico medico1 : medico.EliminarMedicoPorCedula(txt_EliminarMedicoCedula.getText())) {
            model1.addRow(new Object [] {medico1.getCedula(),medico1.getNombre(),medico1.getEspecialidad().getEspecialidad(),medico1.getEdad(),medico1.getSexo()});
        }
    }//GEN-LAST:event_Eliminar

    private void txt_BuscarPorEspecialidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarPorEspecialidadKeyReleased
        // TODO add your handling code here:
        model1.setRowCount(0);
        for (Medico medico1 : medico.MedicosSegunProfesion(txt_BuscarPorEspecialidad.getText())) {
            model1.addRow(new Object [] {medico1.getCedula(),medico1.getNombre(),medico1.getEspecialidad().getEspecialidad(),medico1.getEdad(),medico1.getSexo()});
        }
    }//GEN-LAST:event_txt_BuscarPorEspecialidadKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ListaMedico;
    private javax.swing.JTextField txt_BuscarMedico;
    private javax.swing.JTextField txt_BuscarPorEspecialidad;
    private javax.swing.JTextField txt_BuscarPorNombre;
    private javax.swing.JTextField txt_EliminarMedicoCedula;
    // End of variables declaration//GEN-END:variables
}
