/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Especialidad;

import Controller.EspecialidadControlador;
import Controller.ValidacionController;
import Model.Especialidad;
import Model.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class IngresarEspecialidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarEspeciliddes
     */
    EspecialidadControlador especialidadcontrol = EspecialidadControlador.getinstancia();
    ValidacionController validacioncontrol = ValidacionController.getinstancia();
    Especialidad especialidad2;
    
    public IngresarEspecialidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Especialidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Nombre");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEspecialidad(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Especialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarEspecialidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEspecialidad
        // TODO add your handling code here:
        String especialidad = validacioncontrol.ValidarEspecialidad(txt_Especialidad.getText());
        int contador=0;
        if(especialidad != null)
        {
            for (Especialidad especialidad1 : especialidadcontrol.listaEspecialidad()) {
                if(especialidad1.getEspecialidad().contains(especialidad))
                {
                    JOptionPane.showMessageDialog(this, "YA EXISTE UNA ESPECIALIDAD");
                    contador++;
                }
            }
            if(contador!=1)
            {
                especialidad2 = especialidadcontrol.GuardarEspecialidad(especialidad);
                JOptionPane.showMessageDialog(this, "SE HA GUARDADO LOS DATOS CORRECTAMENTE DEL DR(A): "+especialidad2.getEspecialidad());
                txt_Especialidad.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "NO SE HA PODIDO GUARDAR LOS DATOS");
        }
        txt_Especialidad.setText("");
    }//GEN-LAST:event_GuardarEspecialidad


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_Especialidad;
    // End of variables declaration//GEN-END:variables
}
