/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Citas;

import Controller.CitasController;
import Controller.EspecialidadControlador;
import Controller.MedicoController;
import Controller.PacienteController;
import Controller.ValidacionController;
import Model.Citas;
import Model.Especialidad;
import Model.Medico;
import Model.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class IngresarCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarCitas
     */
    PacienteController pacientecontrol = PacienteController.getInstancia();
    MedicoController medicocontrol = MedicoController.getinstancia();
    CitasController citascontrol = CitasController.getinstancia();
    ValidacionController validacioncontrol = ValidacionController.getinstancia();
    EspecialidadControlador especialidadcontrol = EspecialidadControlador.getinstancia();
    String especialidad;
    
    public IngresarCitas() {
        initComponents();
        listaPacienteComboBox();
        listaEspecialidadComboBox();
        cbx_Medico.addItem("SELECIONOE UN MEDICO");
        cbx_listaespecialidad.addActionListener(e -> {
            especialidad = cbx_listaespecialidad.getSelectedItem().toString();
            //System.out.println(especialidad);
            if(!especialidad.equals("SELECIONE ESPECIALIDAD"))
            {
                cbx_Medico.addItem("SELECIONE UN MEDICO");
                CargarMedicoAutomatico(especialidad);
            }
            else
            {
                cbx_Medico.removeAllItems();
                cbx_Medico.addItem("SELECIONOE UN MEDICO");
            }
        });
    }
    
    private void CargarMedicoAutomatico(String especialidad)
    {
        
        cbx_Medico.removeAllItems();
        cbx_Medico.addItem("SELECIONE UN MEDICO");
        for (Medico medico1 : medicocontrol.MedicosSegunProfesion(especialidad)) {
            cbx_Medico.addItem(medico1.getCedula()+" "+medico1.getNombre());
        }
    }
    
    private void listaPacienteComboBox()
    {
        //Cargo la lista de pacientes en mi COMBOBOX
        cbx_Paciente.addItem("SELECIONE UN PACIENTE");
        for (Paciente paciente1 : pacientecontrol.ListadoPaciente()) {
            cbx_Paciente.addItem(paciente1.getCedula()+" "+paciente1.getNombre());
        }
        /*for (Medico medico1 : medico.ListaMedico()) {
            cbx_Medico.addItem(medico1.getCedula()+" "+medico1.getNombre());
        }*/
    }
    
    private void listaEspecialidadComboBox()
    {
         //Cargo la lista de especialdiades en mi COMBOBOX
        cbx_listaespecialidad.addItem("SELECIONE ESPECIALIDAD");
        for (Especialidad especialidad : especialidadcontrol.listaEspecialidad()) {
            cbx_listaespecialidad.addItem(especialidad.getEspecialidad());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbx_Paciente = new javax.swing.JComboBox<>();
        cbx_Medico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_Observacion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txt_Fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Hora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_listaespecialidad = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Ingresa los Siguientes Datos");

        jLabel2.setText("Paciente");

        jLabel3.setText("Medico");

        jLabel4.setText("Fecha");

        jLabel6.setText("Observaciones");

        txa_Observacion.setColumns(20);
        txa_Observacion.setRows(5);
        jScrollPane1.setViewportView(txa_Observacion);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCita(evt);
            }
        });

        jLabel5.setText("Hora");

        jLabel7.setText("Especialidad");

        jLabel8.setText("dd/mm/aa");

        jLabel9.setText("hh/mm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(txt_Hora))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                                    .addComponent(cbx_Medico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_Paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_listaespecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_listaespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_Medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarCita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCita
        // TODO add your handling code here:
        String paciente1 = cbx_Paciente.getSelectedItem().toString();
        String medico1 = cbx_Medico.getSelectedItem().toString();
        boolean fecha1 = validacioncontrol.ValidacionFecha(txt_Fecha.getText());
        boolean hora1 = validacioncontrol.ValidacionHora(txt_Hora.getText());
        String obserbacion = txa_Observacion.getText();
        String DatosPaciente[] = paciente1.split(" ");
        String CedulaPaciente = DatosPaciente[0];
        String DatosMedico[] = medico1.split(" ");
        String CedulaMedico = DatosMedico[0];
        String fecha = null;
        String hora = null;
        
        if(fecha1 == true)
        {
            fecha = txt_Fecha.getText();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "LA FEHCA ES INCORRECTA");
        }
        
        if(hora1 == true)
        {
            hora = txt_Hora.getText();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "LA HORA ES INCORRECTA");
        }
        
            for (Paciente paciente2 : pacientecontrol.ListadoPaciente()) {
                if(paciente2.getCedula().contains(CedulaPaciente))
                {
                    for (Medico medico2 : medicocontrol.ListaMedico()) {
                        if(medico2.getCedula().contains(CedulaMedico))
                        {
                            Citas turno = citascontrol.GuardarCitas(paciente2, medico2, medico2.getEspecialidad() ,fecha, hora, obserbacion);
                            JOptionPane.showMessageDialog(this, 
                                    "SE HA REGISTRADO LA CITA DEL SR(A): "+turno.getPaciente().getNombre()+
                                    " PARA EL DIA: "+turno.getFecha()+
                                    " A LA HORA: "+turno.getHora()+
                                    " CON EL MEDICO: "+turno.getMedico().getNombre()+
                                    " Y LA ESPECIALIDAD: "+turno.getEspecialidad().getEspecialidad()
                            );
                            txt_Fecha.setText("");
                            txa_Observacion.setText("");
                            txt_Hora.setText("");
                        }
                    }
                }
            }
    }//GEN-LAST:event_GuardarCita


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_Medico;
    private javax.swing.JComboBox<String> cbx_Paciente;
    private javax.swing.JComboBox<String> cbx_listaespecialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_Observacion;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_Hora;
    // End of variables declaration//GEN-END:variables
}
