/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewNotas;

/**
 *
 * @author HP
 */
public class ViewNotas1 extends javax.swing.JFrame {

    /**
     * Creates new form ViewNotas1
     */
    public ViewNotas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Nota1 = new javax.swing.JTextField();
        txt_Nota2 = new javax.swing.JTextField();
        txt_Nota3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_SumaTotal = new javax.swing.JLabel();
        lbl_Promedio = new javax.swing.JLabel();
        lbl_Verificacion = new javax.swing.JLabel();
        lbl_Validacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOTA 1");

        jLabel2.setText("NOTA 2");

        jLabel3.setText("NOTA 3");

        txt_Nota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nota2ActionPerformed(evt);
            }
        });

        jLabel4.setText("SUMA DE NOTAS");

        jLabel5.setText("PROMEDIO NOTAS");

        jLabel6.setText("APRUEBA");

        txt_Resultado.setText("--------------------------------------------");

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatos(evt);
            }
        });

        lbl_SumaTotal.setText("0.00");

        lbl_Promedio.setText("0.00");

        lbl_Verificacion.setText("----------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Nota1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(txt_Nota2)
                                    .addComponent(txt_Nota3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Promedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_SumaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 213, Short.MAX_VALUE))
                                    .addComponent(lbl_Verificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(56, 56, 56))
                    .addComponent(lbl_Validacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Validacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_SumaTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_Promedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_Verificacion))
                .addGap(18, 18, 18)
                .addComponent(txt_Resultado)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarDatos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatos
        double numero1 = Double.parseDouble(txt_Nota1.getText());
        double numero2 = Double.parseDouble(txt_Nota2.getText());
        double numero3 = Double.parseDouble(txt_Nota3.getText());
        double Suma_Total = numero1 +numero2 +numero3;
        double Promedio = Suma_Total/3;
        
        if((numero1 >10 && numero2 >10 && numero3 >10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS  INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >10 && numero2 <=10 && numero3 <=10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <=10 && numero2 >10 && numero3 <=10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 2 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <=10 && numero2 <=10 && numero3 >10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >10 && numero2 >10 && numero3 <=10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1 y 2 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <=10 && numero2 >10 && numero3 >10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 2 y 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >10 && numero2 <=10 && numero3 >10))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1 y 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <0 && numero2 <0 && numero3 <0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <0 && numero2 >=0 && numero3 >=0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >=0 && numero2 <0 && numero3 >=0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 2 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >=0 && numero2 >=0 && numero3 <0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <0 && numero2 <0 && numero3 >=0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1 y 2 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 >=0 && numero2 <0 && numero3 <0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 2 y 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if((numero1 <0 && numero2 >=0 && numero3 <0))
        {
            lbl_Validacion.setText("ERROR. LAS NOTAS 1y 3 INGRESADAS DEBES SER MENORES O IGUALES A 10 Y MAYORES A 0");
        }
        
        if ((numero1 >=0 && numero2 >=0 && numero3 >=0) && (numero1 <=10 && numero2 <=10 && numero3 <=10))
        {
            lbl_SumaTotal.setText(String.valueOf(Suma_Total));
            lbl_Promedio.setText(String.valueOf(String.format("%.2f",Promedio)));
            if(Promedio>=7 && Promedio<=10)
            {
                lbl_Verificacion.setText("SI");
                if(Promedio>=7 && Promedio<8)
                {
                    txt_Resultado.setText("EL ESTUDIANTE APRUEBA CON UNA CALIFICACION REGULAR DE: "+String.format("%.2f",Promedio));   
                }
                if(Promedio>=8 && Promedio<9)
                {
                    txt_Resultado.setText("EL ESTUDIANTE APRUEBA CON UNA CALIFICACION BUENA DE "+String.format("%.2f",Promedio));   
                }
                if(Promedio>=9 && Promedio<=10)
                {
                    txt_Resultado.setText("EL ESTUDIANTE APRUEBA CON UNA CALIFICACION EXCELENTE DE "+String.format("%.2f",Promedio));   
                }
            }
            if(Promedio>=0 && Promedio<7)
            {
                lbl_Verificacion.setText("NO");
                txt_Resultado.setText("EL ESTUDIANTE REPRUEBA CON UNA CALIFICACION DE "+String.format("%.2f",Promedio));
            }
        }
        
    }//GEN-LAST:event_GuardarDatos

    private void txt_Nota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nota2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNotas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNotas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNotas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNotas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNotas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_Promedio;
    private javax.swing.JLabel lbl_SumaTotal;
    private javax.swing.JLabel lbl_Validacion;
    private javax.swing.JLabel lbl_Verificacion;
    private javax.swing.JTextField txt_Nota1;
    private javax.swing.JTextField txt_Nota2;
    private javax.swing.JTextField txt_Nota3;
    private javax.swing.JLabel txt_Resultado;
    // End of variables declaration//GEN-END:variables
}
