/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Citas.IngresarCitas;
import View.Citas.ListadoCita;
import View.Especialidad.IngresarEspecialidad;
import View.Especialidad.ListadoEspecialidad;
import View.Pacientes.IngresarPaciente;
import View.Pacientes.ListadoPaciente;
import View.Medico.IngresarMedico;
import View.Medico.ListadoMedico;

/**
 *
 * @author HP
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        dp_ContenedorPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Menu_Ingresar_Paciente = new javax.swing.JMenuItem();
        Menu_Listado_Paciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        IngresoEspecialidad = new javax.swing.JMenuItem();
        ListadoEspecialidad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dp_ContenedorPrincipal.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("BIENVENDO AL REGISTRO DE CITAS");

        dp_ContenedorPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dp_ContenedorPrincipalLayout = new javax.swing.GroupLayout(dp_ContenedorPrincipal);
        dp_ContenedorPrincipal.setLayout(dp_ContenedorPrincipalLayout);
        dp_ContenedorPrincipalLayout.setHorizontalGroup(
            dp_ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_ContenedorPrincipalLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel1)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        dp_ContenedorPrincipalLayout.setVerticalGroup(
            dp_ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dp_ContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Paciente");

        Menu_Ingresar_Paciente.setText("Ingresar Paciente");
        Menu_Ingresar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Ingresar_PacienteActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Ingresar_Paciente);

        Menu_Listado_Paciente.setText("Listado de Pacientes");
        Menu_Listado_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Listado_PacienteActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Listado_Paciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Especialidad");

        IngresoEspecialidad.setText("Ingresar Especialidad");
        IngresoEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoEspecialidadActionPerformed(evt);
            }
        });
        jMenu3.add(IngresoEspecialidad);

        ListadoEspecialidad.setText("Lista de Especialidad");
        ListadoEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoEspecialidadActionPerformed(evt);
            }
        });
        jMenu3.add(ListadoEspecialidad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Medicos");

        jMenuItem5.setText("Ingresar Medico");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarMedico(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem7.setText("Listado de Medicos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoMedio(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Citas");

        jMenuItem8.setText("Ingresar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Ingresar_Citas(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Listado");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Listado_Citas(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_ContenedorPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_ContenedorPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Ingresar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Ingresar_PacienteActionPerformed
        // TODO add your handling code here:
        //Carge la pantalla de ingresar
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new IngresarPaciente()).setVisible(true);
        
    }//GEN-LAST:event_Menu_Ingresar_PacienteActionPerformed

    private void Menu_Listado_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Listado_PacienteActionPerformed
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new ListadoPaciente()).setVisible(true);
    }//GEN-LAST:event_Menu_Listado_PacienteActionPerformed

    private void IngresarMedico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarMedico
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new IngresarMedico()).setVisible(true);
    }//GEN-LAST:event_IngresarMedico

    private void ListadoMedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoMedio
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new ListadoMedico()).setVisible(true);
    }//GEN-LAST:event_ListadoMedio

    private void Menu_Ingresar_Citas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Ingresar_Citas
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new IngresarCitas()).setVisible(true);
    }//GEN-LAST:event_Menu_Ingresar_Citas

    private void Menu_Listado_Citas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Listado_Citas
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new ListadoCita()).setVisible(true);
    }//GEN-LAST:event_Menu_Listado_Citas

    private void IngresoEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoEspecialidadActionPerformed
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new IngresarEspecialidad()).setVisible(true);
    }//GEN-LAST:event_IngresoEspecialidadActionPerformed

    private void ListadoEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoEspecialidadActionPerformed
        // TODO add your handling code here:
        dp_ContenedorPrincipal.removeAll();
        dp_ContenedorPrincipal.add(new ListadoEspecialidad()).setVisible(true);
    }//GEN-LAST:event_ListadoEspecialidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IngresoEspecialidad;
    private javax.swing.JMenuItem ListadoEspecialidad;
    private javax.swing.JMenuItem Menu_Ingresar_Paciente;
    private javax.swing.JMenuItem Menu_Listado_Paciente;
    private javax.swing.JDesktopPane dp_ContenedorPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
