/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Pacientes;

import Controller.CitasController;
import Controller.PacienteController;
import Controller.ValidacionController;
import Model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class IngresarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingresar
     */
    ValidacionController validacion = ValidacionController.getinstancia();
    PacienteController pacientecontrol = PacienteController.getInstancia();
    Paciente paciente1;
    /*
    String Nombre;
    String cedula;
    int Edad;
    boolean sexo;
    */
    
    public IngresarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_Sexo = new javax.swing.JComboBox<>();
        btn_Guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Sexo");

        cbx_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar(evt);
            }
        });

        jLabel5.setText("Ingrese los Datos Requeridos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel5)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Nombre)
                            .addComponent(txt_Cedula)
                            .addComponent(txt_Edad)
                            .addComponent(cbx_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbx_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Guardar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar
        // TODO add your handling code here:
        String nombre = validacion.ValidacionNombre(txt_Nombre.getText());
        String Cedula = validacion.ValidacionCedula(txt_Cedula.getText());
        int edad = validacion.ValidacionEdad(txt_Edad.getText());
        boolean Sexo = validacion.ValidacionSexo(cbx_Sexo.getSelectedItem().toString());
        boolean validado = validacion.VerificadorDeIngresoDeDatos(nombre, Cedula, edad);
        int contador=0;
        if(validado == true)
        {
            for (Paciente paciente : pacientecontrol.ListadoPaciente()) {
                if(paciente.getCedula().contains(Cedula) && paciente.getNombre().contains(nombre))
                {
                    JOptionPane.showMessageDialog(this, "YA EXISTE UN PACIENTE CON ESTOS DATOS");
                    contador++;
                }
            }
            if(contador!=1)
            {
                paciente1 = pacientecontrol.GuardarPaciente(Cedula, nombre, edad, Sexo);
                JOptionPane.showMessageDialog(this, "SE HA GUARDADO LOS DATOS CORRECTAMENTE DEL PACIENTE: "+paciente1.getNombre());
                txt_Cedula.setText("");
                txt_Nombre.setText("");
                txt_Edad.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "NO SE HA PODIDO GUARDAR LOS DATOS");
        }
        txt_Cedula.setText("");
        txt_Nombre.setText("");
        txt_Edad.setText("");
    }//GEN-LAST:event_Guardar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox<String> cbx_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
