/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Pacientes;

import Controller.PacienteController;
import Model.Paciente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ListadoPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listado
     */
    
    public DefaultTableModel model = new DefaultTableModel();
    PacienteController paciente = PacienteController.getInstancia();
    
    public ListadoPaciente() {
        initComponents();
        tbl_Listado.setModel(model);
        String [] Columnas = {"CEDULA", "NOMBRES", "EDAD", "SEXO"};
        model.setColumnIdentifiers(Columnas);
        ListadoPacientes();
    }
    
    public void ListadoPacientes()
    {
        for (Paciente paciente1 : paciente.ListadoPaciente()) {
            model.addRow(new Object[] {paciente1.getCedula(),paciente1.getNombre(),paciente1.getEdad(),paciente1.getSexo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_BuscarCedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Listado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_BuscarPorNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_EliminiarPacienteCedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Buscar Paciente Por Cedula");

        txt_BuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarCedulaKeyReleased(evt);
            }
        });

        tbl_Listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Listado);

        jLabel2.setText("Listado de Paciente");

        jLabel3.setText("Buscar Paciente Por Nombre");

        txt_BuscarPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarPorNombreKeyReleased(evt);
            }
        });

        jLabel4.setText("Eliminar Paciente Por Cedula");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_BuscarCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txt_BuscarPorNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_EliminiarPacienteCedula))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_BuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_EliminiarPacienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_BuscarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BuscarCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarCedulaKeyReleased
        // TODO add your handling code here:
        //Se busque cuando nosotros ingresamos cuaquier numero de cedula
        model.setRowCount(0);
        for (Paciente paciente1 : paciente.ListadoPacientePorCedula(txt_BuscarCedula.getText())) {
            model.addRow(new Object[] {paciente1.getCedula(),paciente1.getNombre(),paciente1.getEdad(),paciente1.getSexo()});
        }
    }//GEN-LAST:event_txt_BuscarCedulaKeyReleased

    private void txt_BuscarPorNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarPorNombreKeyReleased
        // TODO add your handling code here:
        model.setRowCount(0);
        for (Paciente paciente1 : paciente.ListadoPacientePorNombre(txt_BuscarPorNombre.getText())) {
            model.addRow(new Object[] {paciente1.getCedula(),paciente1.getNombre(),paciente1.getEdad(),paciente1.getSexo()});
        }
    }//GEN-LAST:event_txt_BuscarPorNombreKeyReleased

    private void Eliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar
        // TODO add your handling code here:
        model.removeRow(0);
        for (Paciente paciente1 : paciente.EliminarPacientePorCedula(txt_EliminiarPacienteCedula.getText())) {
            model.addRow(new Object[] {paciente1.getCedula(),paciente1.getNombre(),paciente1.getEdad(),paciente1.getSexo()});
        }
    }//GEN-LAST:event_Eliminar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Listado;
    private javax.swing.JTextField txt_BuscarCedula;
    private javax.swing.JTextField txt_BuscarPorNombre;
    private javax.swing.JTextField txt_EliminiarPacienteCedula;
    // End of variables declaration//GEN-END:variables
}
